[book]
title = "perpus"
authors = ["Fajar Garnadi"]
description = "Miscellaneous stuff."
language = "en"
multilingual = false

[output.html]
no-section-label = true

[output.html.print]
enable = false

[output.html.search]
enable = false
